### PR TITLE
Support for 1.1

### PR DESCRIPTION
**Pull request by emipa606**
.Net update to 4.7.2
Harmony and Hugs references updated via NuGet
Updated About to require Hugs & Harmony
Added package id based on author.modname
Updated Harmony-references
Replaced < with <= in time-comparer to make it more accurate.

Updated the solution to use relative paths and have all contained in the Source-folder since I am using the mod PublisherPlus to publish my mods where you can select folders & files to ignore when publishing to Steam. Just a tip :)

Used my own gitattributes/gitignore files, these can be ignored.

### CODE REVIEW

**Comment by krafs** [comment]
I appreciate the effort you've gone through here, but I'm getting null exceptions when I test it on my machine, right-clicking an alert on screen. But it doesn't matter, I'm planning on adding most of these features in another mod eventually, so I probably won't want Better Notfications updated. They'll conflict. 
But again, thanks for going through the trouble of actually making a PR for this. RW could use more collaboration.

**Comment by emipa606** [comment]
If you are no longer going to maintain this mod, would it be okay if I published the 1.1 version for those who want to continue to use it?

**Comment by krafs** [comment]
Does everything work when you test it on 1.1? Because when I run it, I get errors when I try to right-click alerts (which is one of the main features of the mod).

**Comment by emipa606** [comment]
Yea, my tests went as expected.
Here is the mod-folder raw copy , maybe I missed something in the pull-request
[BetterNotifications.zip](https://github.com/krafs/BetterNotifications/files/4470739/BetterNotifications.zip)

**Comment by krafs** [comment]
I'm still getting errors when right-clicking an active alert, even with a clean test environment. You may look at the log if you're interested.
[Player.log](https://github.com/krafs/BetterNotifications/files/4470815/Player.log)

It is ok if you want to publish it. But I suggest you look into the error I got. It might just be something on my local machine, but you might want to make sure, so as to avoid the risk of angry workshop comments :)

**Pull request closed without merging**
